on: push

jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          git config user.name "wisdom"
          git config user.email "your.email@example.com"
          git add .
          git commit -m "file modification"
          git push
