jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to gh-pages
        run: |
          git config user.name "programmingbymaleek"
          git config user.email "your.email@example.com"
          git add .
          git commit -m "file modification"
          git push
